language: php
php:
  - 5.5
  - 5.4

before_script:
  - mkdir -p build/logs
  - composer install
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

services:
  - mongodb

script:
  - vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml test/

after_success:
 - php vendor/bin/coveralls -v