language: php
php:
  - 5.5
  - 5.4
services:
  - mongodb
before_script:
  - composer install
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: vendor/phpunit/phpunit/phpunit test/